<?php
/** ============================================================
 * Contains common function and Error handling API.
 * @package core
 * @see conf.class.php
 * ============================================================ */
class Common
{
    /** Error messages.
     * @var array
     */
    var $aErrors = array();


    /** Default constructor (empty)
     * @return Common
     */
    function Common() { }

    /** Returns all errors generated by object
     * @return array errors
     */
    function getErrors()
    {
        return $this->aErrors;
    }

    /** Adds an error to object error pool.
     * @param string  $sKey   key of error message
     * @param mixed   $aParm  paramteres of error message
     * @param boolean $bFatal true - fatal error, false (deafult) - recoverable error
     * @return boolean false
     */
    function _addError($sKey, $mParam=array(), $bFatal=false)
    {
        if ($mParam && !is_array($mParam))
            $mParam = array($mParam);

        $sErr = Conf::format($sKey, $mParam);
        $this->aErrors[] = $sErr;
        if ($bFatal)
        {
            //see trigger_error
            trigger_error(substr($sErr, 0, 1024), E_USER_ERROR);
            exit;
        }
        return false;
    }
    
}
?>
